flags:
  snap-server:
    openssl: true
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/Soostone/snaplet-persistent.git
    commit: 8bdbd542006b27eca936feb1cb147f26e5f8c602
extra-deps:
- cond-0.4.1.1
- snap-loader-static-0.9.0.2
- snap-server-0.9.5.1
resolver: lts-5.11
